[package]
name = "rust-ktane-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
image = {version = "0.24.5", default-features = false, features = ["png"]}